GET http://localhost:8000/business/
Accept: application/json

###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list?page=1&size=10&trainCode=G1&date=2024-02-22&start=%E6%B7%B1%E5%9C%B3&end=%E4%B8%8A%E6%B5%B7
